version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/thor_database
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: thor_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thor_database
    ports:
      - "5433:5432" # Cambiamos el puerto externo a 5433
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


